on:
  push:

name: Deploy to the gh-pages branch.

jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: github.ref == 'refs/heads/live'
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
